import json
p = str(Path(__file__).resolve().parent.parent / "01_data" / "market" / "market_timing_input.json")
d=json.load(open(p,encoding='utf-8'))
print('collector', d['collector_version'])
print('indices', {k:v.get('intraday') for k,v in d['a_share_indices'].items()})
print('breadth', d['market_breadth'])
print('sentiment', d['sentiment'])
print('turnover', d['turnover'])
print('quality notes', d['data_quality'].get('notes'))
print('sc raw', d['data_quality'].get('sc_fields_raw'))
